sendErrorOptIn:  true
jobs:
  download-dev:
    current:
        scripts:
        - folderPath:  ../state
    target:
        adx:
            clusterUri:  to-be-overriden
            database:  dev
    action:
        pushToConsole:  true
        filePath:  kql-scripts/delta.kql
tokenProvider:
    login:
        tenantId:  to-be-overriden
        clientId:  to-be-overriden
        secret:  to-be-overriden