# YAML doc:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

resources:
- repo: self
# Triggers:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#triggers
# No trigger for this one as it is meant to be triggered manually only
trigger: []

# Stages:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#stage
stages:
- stage:  rev_engineer
  displayName:  Reverse Engineer Database
  variables:  []
  jobs:
  - job:  delta_kusto
    pool:
      vmImage: 'ubuntu-latest'
    variables:  []
    steps:
    # Bash script:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#bash
    - bash:  |
        clientVersion=$(curl https://delta-kusto.azurefd.net/clientVersion/unique?fromClientVersion=0)
        # Display the version on console
        echo "Client Version:  $clientVersion"
        wget https://github.com/microsoft/delta-kusto/releases/download/$clientVersion/delta-kusto-linux.tar.gz
        tar --extract --file delta-kusto-linux.tar.gz
        chmod +x ./delta-kusto
      displayName:  Install Delta-Kusto
    - bash:  |
        clusterUri=${{ variables.TENANT_ID }}
        echo "Cluster URI:  $clusterUri"
        # Package the login in a JSON payload
        login='{"tenantId":"${{ variables.TENANT_ID }}","clientId":"${{ variables.CLIENT_ID }}","secret":"${{ variables.SECRET }}"}'
        ./delta-kusto -p documentation/tutorials/az-dev-ops/reverse-engineer.yaml -o tokenProvider.login=$login jobs.download-dev.target.adx.clusterUri=$clusterUri
      displayName:  Run Delta-Kusto