name:  API Azure Infra

on:  workflow_dispatch

env:
  rg:  gram-parser

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Login
    - name: Azure Login
      run: az login --service-principal -u ${{ secrets.sp_id }} -p ${{ secrets.sp_secret }} --tenant ${{ secrets.tenant_id }}
    # Deploy
    - name: Deploy
      run: |
        cd deployment
        bash deploy-api-infra.sh ${{ secrets.api_rg }}