name:  API Infra

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - deployment/api/api-infra-deploy.json
      - .github/workflows/api-infra.yaml

env:
  rg:  ---

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Login
    - name: Azure Login
      run: az login --service-principal -u ${{ secrets.deploy_sp_id }} -p ${{ secrets.deploy_sp_secret }} --tenant ${{ secrets.tenant_id }}
    # Deploy
    - name: Deploy
      run: |
        cd deployment/api
        bash deploy-api-infra.sh ${{ secrets.api_rg }}