name:  Integration Test Infra

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - deployment/integration-test
      - .github/workflows/integration-test-infra.yaml

env:
  rg:  ---

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Login
    - name: Azure Login
      run: az login --service-principal -u ${{ secrets.deploy_sp_id }} -p ${{ secrets.deploy_sp_secret }} --tenant ${{ secrets.tenant_id }}
    # Deploy
    - name: Deploy
      run: |
        cd deployment/integration-test
        bash deploy-integration-test-infra.sh ${{ secrets.api_rg }} ${{ secrets.tenant_id }} ${{ secrets.deploy_sp_id }}