name:  Release

on:  workflow_dispatch


jobs:
  linux:

    runs-on: ubuntu-latest
    
    env:
      os:  linux
      dotnetOs:  linux-x64

    steps:
    - uses: actions/checkout@v2
    - name:  Output full version
      run:  |
        echo "Branch:  ${{ github.ref }}"
    - name: Patch version
      id:  patch-version
      run: python3 deployment/patch-version.py code/delta-kusto/delta-kusto.csproj ${{ github.run_number }}
    - name:  Output full version
      run:  |
        echo "Full version:  ${{ steps.patch-version.outputs.full-version }}"
    # - name: Tag
    #   run: |
    #     git tag test
    #     git push --tags
