name:  Release

on:
  workflow_dispatch:
  push:
    branches:
      - release/*

jobs:
  linux:

    # Eventually, this should be multi-platform ; see https://stackoverflow.com/questions/57498605/github-actions-share-workspace-artifacts-between-jobs
    runs-on: ubuntu-latest
    
    env:
      os:  linux
      dotnetOs:  linux-x64

    steps:
    - uses: actions/checkout@v2
    - name: gh
      run:  |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
        gh repo list
    - name: Patch version
      id:  patch-version
      run: python3 deployment/patch-version.py code/delta-kusto/delta-kusto.csproj ${{ github.run_number }}
    - name:  Output full version
      run:  |
        echo "Full version:  ${{ steps.patch-version.outputs.full-version }}"
    # See https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore
    - name: Install dependencies
      run: dotnet restore code
    # See https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build
    - name: Build
      run: dotnet build code --configuration Release --no-restore
    # See https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test
    - name: Unit Tests
      run: dotnet test code/DeltaKustoUnitTest --configuration Release --no-build --verbosity normal
    # See https://github.com/dotnet/designs/blob/main/accepted/2020/single-file/design.md#user-experience
    # & https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file
    # & https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish
    - name: Build single file executable
      run: |
        dotnet publish code/delta-kusto -c release -r $dotnetOs \
          -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true \
          -p:PublishTrimmed=true -p:PublishReadyToRun=true \
          -o bin
    # - name: Tag
    #   run: |
    #     git tag test
    #     git push --tags
