name:  Release

on:  workflow_dispatch


jobs:
  linux:

    runs-on: ubuntu-latest
    
    env:
      os:  linux
      dotnetOs:  linux-x64

    steps:
    - uses: actions/checkout@v2
    - name: Tag
      run: |
        git tag test
        git push --tags
