name:  Windows Exec tests (temp)

on:  workflow_dispatch

jobs:
  windows:

    runs-on: windows-latest
    
    env:
      # os:  linux
      dotnetOs:  win-x64

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    # See https://github.com/dotnet/designs/blob/main/accepted/2020/single-file/design.md#user-experience
    # & https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file
    # & https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish
    - name: Build single file executable
      shell:  bash
      run: |
        dotnet publish code/delta-kusto -c release -r $dotnetOs \
          -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true \
          -p:PublishTrimmed=true -p:PublishReadyToRun=true \
          -o bin
    # Set environment variables
    - name: Set environment variables
      shell:  bash
      run: |
        # Exec path
        echo "deltaKustoSingleExecPath=$(pwd)/bin/delta-kusto.exe" >> $GITHUB_ENV
        # ADX integration
        echo "deltaKustoClusterUri=${{ secrets.CLUSTER_URI }}" >> $GITHUB_ENV
        echo "deltaKustoCurrentDb=${{ secrets.CURRENT_DB }}" >> $GITHUB_ENV
        echo "deltaKustoTargetDb=${{ secrets.TARGET_DB }}" >> $GITHUB_ENV
        echo "deltaKustoTenantId=${{ secrets.TENANT_ID }}" >> $GITHUB_ENV
        echo "deltaKustoSpId=${{ secrets.KUSTO_SP_ID }}" >> $GITHUB_ENV
        echo "deltaKustoSpSecret=${{ secrets.KUSTO_SP_SECRET }}" >> $GITHUB_ENV
    # See https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test
    - name: File-based integration tests (out-of-proc)
      shell:  bash
      run: |
        # Disable parallelization of tests
        # See https://xunit.net/docs/running-tests-in-parallel
        dotnet test code/DeltaKustoFileIntegrationTest \
        --configuration Release --no-build --verbosity normal \
        -p:ParallelizeTestCollections=false

    # See https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test
    - name: ADX-based integration tests (out-of-proc)
      shell:  bash
      run: |
        # Disable parallelization of tests
        # See https://xunit.net/docs/running-tests-in-parallel
        dotnet test code/DeltaKustoAdxIntegrationTest \
        --configuration Release --no-build --verbosity normal \
        -p:ParallelizeTestCollections=false


  # #   runs-on: windows-latest

  # #   env:
  # #     singleFilePath:  bin/delta-single-file.exe
  # #     os:  windows

